void main(){
  String ilce = "Ümraniye";
  String kita = "Amerika";
  String fax = "+90543 586 90 87";
  int postaKodu = 34091;
  String instaAdres = "@urban_vibes_daily";
  String calistigiBolum = "Flutter Developer";
  int urunMiktari = 120;
  String musteriSoyadi = "Akdoğan";
  double odemeMiktari = 3465.56;
  String dogumTarihi = "18-11-2000";
  double borc = 23451.345;
  String medeniHal = "Evli";
  String videoYorum = "Güzel";
  String odemeSaati = "13:30";
  double eftMiktari = 78.30;
  double satilanMiktar = 1234.56;
  String telefonModeli = "Samsung Galaxy A52";
  String dergiAdi = "Bilim Çocuk";
  String basimTarihi = "13-02-1978";
  double zamMiktari = 2.5;
  int daireSayisi = 6;
  String enlem = "37.7749°N";
  String boylam = "122.4194°W";
  String yemekAdi ="Mantı";
  double urunFiyati = 19.99;
  String sirket = "Codeway";
  String videoAdi = "Exploring Hidden Gems: A Day in the City";
  double muzikSuresi = 3.45;
  double mekanPuani = 3.6;
  String dosyaAdi = "project_notes.txt";
  String resimFormati = "PNG";
  String renk = "Mavi";
  String renkKodu ="#FFFFFFF";
  String bilgisayarModeli = "Huawei MateBook D16";
  String ekranBoyutu = "2560 x 1440(QHD)";
  String kullanimSuresi = "3 saat 45 dakika";
  int basinc = 1013;
  String etkinlikGunu = "Pazartesi";
  String odemeGunu = "Çarşamba";
  String yolculukCikisTarihi = "15-06-2024";
  String mahalleAdi = "Yıldırım mah.";
  String otobusHatti = "B24";
  String kullanilanDakika = "57 dakika";
  String kargoTakipNo = "TR1234567890";
  String kuponSuresi = "3 gün";
  String kuponKodu = "SAVE20NOW";
  String faturaTarihi = "12-12-2024";

  print("İlçe                  :  $ilce");
  print("Kıta                  :  $kita");
  print("Faks                  :  $fax");
  print("Posta Kodu            :  $postaKodu");
  print("İnsta Adresi          :  $instaAdres");
  print("Çalıştığı Bölüm       :  $calistigiBolum");
  print("Ürün Miktarı          :  $urunMiktari");
  print("Müşteri Soyadı        :  $musteriSoyadi");
  print("Ödeme Miktarı         :  $odemeMiktari");
  print("Doğum Tarihi          :  $dogumTarihi");
  print("Borç                  :  $borc");
  print("Medeni Hal            :  $medeniHal");
  print("Video Yorumu          :  $videoYorum");
  print("Ödeme Saati           :  $odemeSaati");
  print("Eft Miktarı           :  $eftMiktari");
  print("Satılan Miktar        :  $satilanMiktar");
  print("Telefon Modeli        :  $telefonModeli");
  print("Dergi Adı             :  $dergiAdi");
  print("Basım Tarihi          :  $basimTarihi");
  print("Zam Miktarı           :  $zamMiktari");
  print("Daire Sayısı          :  $daireSayisi");
  print("Enlem                 :  $enlem");
  print("Boylam                :  $boylam");
  print("Yemek Adı             :  $yemekAdi");
  print("Ürün Fiyatı           :  $urunFiyati");
  print("Şirket                :  $sirket");
  print("Video Adı             :  $videoAdi");
  print("Müzik Süresi          :  $muzikSuresi");
  print("Mekan Puanı           :  $mekanPuani");
  print("Dosya Adı             :  $dosyaAdi");
  print("Resim Formatı         :  $resimFormati");
  print("Renk                  :  $renk");
  print("Renk Kodu             :  $renkKodu");
  print("Bilgisayar Modeli     :  $bilgisayarModeli");
  print("Ekran Boyutu          :  $ekranBoyutu");
  print("Kullanım Süresi       :  $kullanimSuresi");
  print("Basınç                :  $basinc");
  print("Etkinlik Günü         :  $etkinlikGunu");
  print("Ödeme Günü            :  $odemeGunu");
  print("Yolculuk Çıkış Tarh.  :  $yolculukCikisTarihi");
  print("Mahalle Adı           :  $mahalleAdi");
  print("Otobüs Hattı          :  $otobusHatti");
  print("Kullanılan Dakika     :  $kullanilanDakika");
  print("Kargo Takip No        :  $kargoTakipNo");
  print("Kupon Süresi          :  $kuponSuresi");
  print("Kupon Kodu            :  $kuponKodu");
  print("Fatura Tarihi         :  $faturaTarihi");
}